export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENT = 'SET_INGREDIENT';
export const FETCH_INGREDIENT_FAILED = 'FETCH_INGREDIENT_FAILED';
export const CLEAR_ORDER = 'CLEAR_ORDER';
export const INIT_INGREDIENT_REQUEST = 'INIT_INGREDIENT_REQUEST';

export const PURCHASES_BURGER_REQUEST = 'PURCHASES_BURGER_REQUEST'
export const PURCHASES_BURGER_START = 'PURCHASES_BURGER_START'
export const PURCHASES_BURGER_SUCCESS = 'PURCHASES_BURGER_SUCCESS';
export const PURCHASES_BURGER_FAILED = 'PURCHASES_BURGER_FAILED';
export const PURCHASES_BURGER_INIT = 'PURCHASES_BURGER_INIT';

export const FETCH_ORDERS_REQUEST = 'FETCH_ORDERS_REQUEST';
export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILED = 'FETCH_ORDERS_FAILED';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_AUTO_LOGOUT = 'AUTH_AUTO_LOGOUT';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_INITIATE = 'AUTH_INITIATE';
export const AUTH_CHECK_STATUS = 'AUTH_CHECK_STATUS';
